GET HTTP://localhost:8080/api/categorias

###

POST HTTP://localhost:8080/api/categorias
Content-Type: application/json

{
    "nome": "smartphone3"
}

###

POST HTTP://localhost:8080/api/categorias
Content-Type: application/json

{
    "nome": "tv"
}

###

PUT HTTP://localhost:8080/api/categorias/1
Content-Type: application/json

{
    "nome": "smartphone"
}

###

DELETE HTTP://localhost:8080/api/categorias/3
    

