GET HTTP://localhost:8080/api/clientes

###

GET HTTP://localhost:8080/api/clientes/1

###

POST HTTP://localhost:8080/api/clientes
Content-Type: application/json

{
    "nome": "Gabriell",
    "idade": 19,
    "email": "gablima004@gmail.com",
    "cpf": "16836337765"
}

###

POST HTTP://localhost:8080/api/clientes
Content-Type: application/json

{
    "nome": "Luiz Gabriel",
    "idade": 31,
    "email": "luiz@gmail.com",
    "cpf": "88926176720"
}

###

PUT HTTP://localhost:8080/api/clientes/1
Content-Type: application/json

{
    "nome": "Gabriel Lima",
    "idade": 19,
    "email": "gablima004@gmail.com",
    "cpf": "16836337765"
}

###

DELETE HTTP://localhost:8080/api/clientes/4
    

