GET HTTP://localhost:8080/api/enderecos

###

POST HTTP://localhost:8080/api/enderecos
Content-Type: application/json

{   
    "cliente": {
        "id": 1
    },
    "cep": "26900000",
    "rua": "Rua 1",
    "bairro": "Bairro 1",
    "cidade": "Cidade 1",
    "estado": "Estado 1",
    "complemento": "Complemento 1",
    "numero": 134
}

###

POST HTTP://localhost:8080/api/enderecos
Content-Type: application/json

{   
    "cliente": {
        "id": 2
    },
    "cep": "26911222",
    "rua": "Rua 2",
    "bairro": "Bairro 2",
    "cidade": "Cidade 2",
    "estado": "Estado 2",
    "complemento": "Complemento 2",
    "numero": 431
}

###

PUT HTTP://localhost:8080/api/enderecos/1
Content-Type: application/json

{
    "cep": "26900000",
    "rua": "Travessa Vereador José de Souza",
    "bairro": "Recreio",
    "cidade": "Miguel Pereira",
    "estado": "Rio de Janeiro",
    "coplemento": "Centro",
    "numero": 134
}

###

DELETE HTTP://localhost:8080/api/enderecos/3
    

