GET HTTP://localhost:8080/api/produtos

###

GET HTTP://localhost:8080/api/produtos/categoria/smatphone
###

GET HTTP://localhost:8080/api/produtos/1

###

POST HTTP://localhost:8080/api/produtos
Content-Type: application/json

{
    "nome": "Iphone 12",
    "marca": "APPLE",
    "categoria": {
        "id": 1
    },
    "preco": 650.0,
    "descricao": "Produto 11"
}

###

POST HTTP://localhost:8080/api/produtos
Content-Type: application/json

{
    "nome": "TV SAMSUNG",
    "marca": "SAMSUNG",
    "categoria": {
        "id": 2
    },
    "preco": 650.0,
    "descricao": "TV 4K 55"
}

###

PUT HTTP://localhost:8080/api/produtos/1
Content-Type: application/json

{
    "nome": "Iphone 12",
    "marca": "APPLE",
    "categoria": {
        "id": 1
    },
    "preco": 750.0,
    "descricao": "Produto 12"
}

###

DELETE HTTP://localhost:8080/api/produtos/2
    

